// Automatically generated by astro-icon
// 696562e595282876432cf32e3dbfd56c59165cd03f57540ca048b3981ecd006f

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "alarm"
		| "brush"
		| "devices"
		| "sos"
		| "success";
}